### PR TITLE
fix: change mongodb-boltdb-mock deleted repo ref to new SHA

### LINKED ISSUE #79: Uses no longer accessible dependencies
**Describe the bug**
`go-health` depends on [mongodb-boltdb-mock](github.com/zaffka/mongodb-boltdb-mock) which is no longer accessible

Although this dependency is not used directly, it stops dependabot from working properly as it appears in the go.sum file of the projects depending on `go-health`
image

Could the dependency be removed and an alternative chosen?

### PR DESCRIPTION
**Pull request by ivan-santos-eq**
fixes #79

### CODE REVIEW

**Review by jdaftari-confluent — APPROVED** [review]
LGTM

**Review by codyaray — APPROVED** [review]
+1, can we get this merged?

**Review by chesleybrown — APPROVED** [review]

**Comment by chesleybrown** [comment]
Is this PR still needed? It looks like the repo was restored: https://github.com/zaffka/mongodb-boltdb-mock

Screen Shot 2022-10-18 at 12 39 14 PM

**Comment by codyaray** [comment]
Yeah, the PR is still needed to fix the SHA sums, otherwise golang won't build right. (It wasn't "restored" so much as "a new repo was created with a copy of the files... and thus all the hashes are different)

**Comment by codyaray** [comment]
Thank you so much for the quick response, @chesleybrown !

**Pull request merged**
