### PR TITLE
Memcached

### PR DESCRIPTION
**Pull request by helios-ag**
Added simple memcached check.

### CODE REVIEW

**Comment by dselans** [comment]
Thanks for another contribution! The tests are panic'ing for some reason (and codecov isn't getting ran) - I'll take a look at that and then review the PR.

**Comment by dselans** [comment]
Please test the following cases: https://codecov.io/gh/InVisionApp/go-health/pull/52/diff?src=pr&el=tree#D1-142...159

This way we do not keep lowering our codecov.

**Review by dselans — CHANGES_REQUESTED** [review]
Thanks for the contribution! Please test these code paths: https://codecov.io/gh/InVisionApp/go-health/pull/52/diff?src=pr&el=tree#D1-142...159

Same as before - goal is to keep >95% test cov. Once that’s good, we can merge away and put out a new release :)

**Comment by helios-ag** [comment]
Sure, will update soon.

**Comment by dselans** [comment]
I was referring to this part: https://codecov.io/gh/InVisionApp/go-health/pull/52/diff?src=pr&el=tree#D1-147

As in, testing that `validateMemcachedConfig` sets Value to default if its left blank.

With that said, this is fine - you've tested New* and satisfied most of the other test cases. Let's get this merged!

**Review by dselans — APPROVED** [review]

**Pull request merged**
